name: Android CI

on: push

jobs:
  test:

    runs-on: macos-10.15
    env:
      GPR_USER: ${{ secrets.GPR_USER }}
      GPR_API_KEY: ${{ secrets.GPR_API_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Run Instrumentation Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedCheck -x :sample:connectedCheck

  publish:
    needs: test
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish Core Library
        run: ./gradlew app-performance-tracker-core:bintrayUpload -PbintrayUser="${{ secrets.BINTRAY_USER }}" -PbintrayKey="${{ secrets.BINTRAY_KEY }}" -PdryRun=false
      - name: Publish Firebase Library
        run: ./gradlew app-performance-tracker-firebase:bintrayUpload -PbintrayUser="${{ secrets.BINTRAY_USER }}" -PbintrayKey="${{ secrets.BINTRAY_KEY }}" -PdryRun=false